{
    'name': 'Estado de Cuenta - Reporte de Clientes',
    'version': '19.0.4.5.2',
    'category': 'Sales/Sales',
    'summary': 'Reporte PDF de estado de cuenta por cliente y/o proyecto',
    'author': 'Alphaqueb Consulting SAS',
    'website': 'https://alphaqueb.com',
    'depends': [
        'sale',
        'sale_stock',
        'account',
        'web',
        'stock',
        'sale_delivery_wizard',
        'sale_order_extended_metrics',
    ],
    'data': [
        'views/account_move_views.xml',
        'security/ir.model.access.csv',
        'wizard/account_statement_wizard_views.xml',
        'report/account_statement_report.xml',
        'report/account_statement_templates.xml',
        'views/menu_views.xml',
        'views/sale_order_views.xml',
        'security/add_groups.xml',
        'security/add/ir.model.access.csv',
        'security/add_rules.xml',
        'views/add_views.xml',
        'views/res_users_add_views.xml',
        'data/add_cron.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'account_statement_report/static/src/add/explorer.js',
            'account_statement_report/static/src/add/explorer.xml',
            'account_statement_report/static/src/add/explorer.scss',
            'account_statement_report/static/src/add/dashboard.js',
            'account_statement_report/static/src/add/dashboard.xml',
            'account_statement_report/static/src/add/dashboard.scss',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
